// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmfVQQx_VBTnfB4xNtP4EHUvzXImVebI',
    appId: '1:695449332360:web:c8022c83bb0e202a0a0d3d',
    messagingSenderId: '695449332360',
    projectId: 'avlyn-demo-app',
    authDomain: 'avlyn-demo-app.firebaseapp.com',
    storageBucket: 'avlyn-demo-app.appspot.com',
    measurementId: 'G-QK4CHWVFTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1DxiXZEqMI6EvrfYSYbiZAlMmWSTrUQ',
    appId: '1:695449332360:android:c275bcc726d8840d0a0d3d',
    messagingSenderId: '695449332360',
    projectId: 'avlyn-demo-app',
    storageBucket: 'avlyn-demo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZFb7stn0RLrlb3gN0Rf7hOring_EKrU',
    appId: '1:695449332360:ios:f95dce21d1f76df20a0d3d',
    messagingSenderId: '695449332360',
    projectId: 'avlyn-demo-app',
    storageBucket: 'avlyn-demo-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZFb7stn0RLrlb3gN0Rf7hOring_EKrU',
    appId: '1:695449332360:ios:f95dce21d1f76df20a0d3d',
    messagingSenderId: '695449332360',
    projectId: 'avlyn-demo-app',
    storageBucket: 'avlyn-demo-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwmfVQQx_VBTnfB4xNtP4EHUvzXImVebI',
    appId: '1:695449332360:web:c40f75f9138d4f470a0d3d',
    messagingSenderId: '695449332360',
    projectId: 'avlyn-demo-app',
    authDomain: 'avlyn-demo-app.firebaseapp.com',
    storageBucket: 'avlyn-demo-app.appspot.com',
    measurementId: 'G-9PX3XHD5CS',
  );
}
